tour_data = [
    {
        'id': 1,
        'title': 'Coyoacán & Frida Kahlo Free Walking Tour in Mexico City',
        'description': 'Enjoy the enchanted blocks around the famed "Blue House" where the wonderful Mexican artist Frida Kahlo used to live, and learn how she became a significant icon around the world.',
        'hour': '2:30 PM',
        'duration': '2.5 hours',
        'language': 'English',
        'meeting_point': "Frida Kahlo's Museum",
        'price': 'Based on tips',
        'image': 'https://images.pexels.com/photos/6424244/pexels-photo-6424244.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': 'https://www.eventbrite.com/e/coyoacan-frida-kahlo-free-walking-tour-in-mexico-city-tickets-377448397317?aff=odcleoeventsincollection&keep_tld=1',
    },
    {
        'id': 2,
        'title': 'Teotihuacan Pyramids Guided Tour',
        'description': 'Explore the ancient Teotihuacan Pyramids, a UNESCO World Heritage site, and learn about the fascinating history and culture of this ancient city.',
        'hour': '9:00 AM',
        'duration': '4 hours',
        'language': 'Spanish',
        'meeting_point': 'Teotihuacan Visitor Center',
        'price': '$30.00 per person',
        'image': 'https://images.pexels.com/photos/4092171/pexels-photo-4092171.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 3,
        'title': 'Chapultepec Castle and Park Tour',
        'description': 'Discover the history and elegance of Chapultepec Castle, situated in the heart of Chapultepec Park, and enjoy a stroll through the beautiful surrounding gardens.',
        'hour': '11:00 AM',
        'duration': '3 hours',
        'language': 'English',
        'meeting_point': 'Chapultepec Castle Entrance',
        'price': '$25.00 per person',
        'image': 'https://images.pexels.com/photos/16138160/pexels-photo-16138160/free-photo-of-rascacielos-pavimento-urbano-mexico.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 4,
        'title': 'Xochimilco Floating Gardens Boat Tour',
        'description': 'Experience the vibrant colors and cultural richness of Xochimilco as you navigate its picturesque canals on a traditional trajinera boat.',
        'hour': '1:00 PM',
        'duration': '2 hours',
        'language': 'Spanish',
        'meeting_point': 'Xochimilco Dock',
        'price': '$20.00 per person',
        'image': 'https://images.unsplash.com/photo-1564762332974-5bf63a654c9d?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        'url': '',
    },
    {
        'id': 5,
        'title': 'Zócalo and Historic Center Walking Tour',
        'description': 'Walk through the historic heart of Mexico City, the Zócalo, and explore its iconic landmarks, including the Metropolitan Cathedral and the National Palace.',
        'hour': '10:30 AM',
        'duration': '2.5 hours',
        'language': 'English',
        'meeting_point': 'Zócalo Square',
        'price': '$15.00 per person',
        'image': 'https://images.pexels.com/photos/12331682/pexels-photo-12331682.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 6,
        'title': 'Street Food Tasting in La Merced Market',
        'description': 'Embark on a culinary adventure in the bustling La Merced Market, tasting a variety of authentic Mexican street foods and flavors.',
        'hour': '6:00 PM',
        'duration': '2 hours',
        'language': 'Spanish',
        'meeting_point': 'La Merced Market Entrance',
        'price': '$18.00 per person',
        'image': '',
        'url': '',
    },
    {
        'id': 7,
        'title': 'National Museum of Anthropology Guided Tour',
        'description': 'Explore the extensive collection of pre-Columbian artifacts and learn about the diverse cultures that shaped the history of Mexico at the National Museum of Anthropology.',
        'hour': '3:00 PM',
        'duration': '3 hours',
        'language': 'English',
        'meeting_point': 'National Museum of Anthropology Entrance',
        'price': '$22.00 per person',
        'image': 'https://images.pexels.com/photos/3680770/pexels-photo-3680770.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
]

rome_tour_data = [
    {
        'id': 8,
        'title': 'Colosseum and Roman Forum Guided Tour',
        'description': 'Explore the iconic Colosseum and Roman Forum with a knowledgeable guide, delving into the rich history of ancient Rome.',
        'hour': '9:30 AM',
        'duration': '3 hours',
        'language': 'English',
        'meeting_point': 'Colosseum Entrance',
        'price': '€40.00 per person',
        'image': 'https://images.pexels.com/photos/2853961/pexels-photo-2853961.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 9,
        'title': 'Vatican City Highlights Tour',
        'description': 'Visit the Vatican City, home to St. Peter\'s Basilica and the Sistine Chapel, and marvel at the masterpieces of art and architecture.',
        'hour': '10:00 AM',
        'duration': '4 hours',
        'language': 'Italian',
        'meeting_point': 'Vatican Museum Entrance',
        'price': '€50.00 per person',
        'image': 'https://images.pexels.com/photos/2631611/pexels-photo-2631611.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 10,
        'title': 'Trastevere Evening Food Tour',
        'description': 'Indulge in the culinary delights of Trastevere, sampling authentic Italian dishes and exploring the charming streets of this historic neighborhood.',
        'hour': '6:30 PM',
        'duration': '3 hours',
        'language': 'English',
        'meeting_point': 'Trastevere Square',
        'price': '€35.00 per person',
        'image': 'https://images.pexels.com/photos/2567377/pexels-photo-2567377.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 11,
        'title': 'Pantheon and Piazza Navona Walking Tour',
        'description': 'Stroll through the historic streets of Rome, visiting the iconic Pantheon and Piazza Navona, and learn about the city\'s fascinating past.',
        'hour': '11:00 AM',
        'duration': '2.5 hours',
        'language': 'Italian',
        'meeting_point': 'Pantheon Square',
        'price': '€25.00 per person',
        'image': 'https://images.pexels.com/photos/1239509/pexels-photo-1239509.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 12,
        'title': 'Catacombs of Rome Underground Tour',
        'description': 'Descend into the fascinating world of Romes catacombs, exploring underground burial sites and learning about ancient Roman burial customs.',
        'hour': '2:00 PM',
        'duration': '3 hours',
        'language': 'English',
        'meeting_point': 'Catacombs Entrance',
        'price': '€30.00 per person',
        'image': 'https://images.pexels.com/photos/4887137/pexels-photo-4887137.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 13,
        'title': 'Trevi Fountain and Spanish Steps Evening Tour',
        'description': 'Experience the enchanting beauty of Rome at night, visiting the iconic Trevi Fountain and Spanish Steps under the city lights.',
        'hour': '8:00 PM',
        'duration': '2 hours',
        'language': 'Italian',
        'meeting_point': 'Trevi Fountain',
        'price': '€20.00 per person',
        'image': 'https://images.pexels.com/photos/1264463/pexels-photo-1264463.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 14,
        'title': 'Rome Bike Tour: Highlights and Hidden Gems',
        'description': 'Cycle through the streets of Rome, discovering both famous landmarks and hidden gems, with a local guide leading the way.',
        'hour': '10:00 AM',
        'duration': '3.5 hours',
        'language': 'English',
        'meeting_point': 'Bike Rental Shop',
        'price': '€28.00 per person',
        'image': 'https://images.pexels.com/photos/6111382/pexels-photo-6111382.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 15,
        'title': 'Rome Street Art Tour in Testaccio',
        'description': 'Explore the vibrant street art scene in the Testaccio neighborhood, discovering colorful murals and the stories behind them.',
        'hour': '3:30 PM',
        'duration': '2 hours',
        'language': 'Italian',
        'meeting_point': 'Testaccio Square',
        'price': '€18.00 per person',
        'image': 'https://images.pexels.com/photos/1575815/pexels-photo-1575815.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 16,
        'title': 'Rome Cooking Class: Pasta Making Experience',
        'description': 'Join a hands-on pasta making class in Rome, learning the art of crafting traditional Italian pasta dishes from scratch.',
        'hour': '5:00 PM',
        'duration': '2.5 hours',
        'language': 'English',
        'meeting_point': 'Cooking School',
        'price': '€45.00 per person',
        'image': 'https://images.pexels.com/photos/2138825/pexels-photo-2138825.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 17,
        'title': 'Rome Wine Tasting: Vino and Cicchetti Tour',
        'description': 'Savor the flavors of Italian wine and cicchetti (small snacks) on a guided tasting tour through the charming streets of Rome.',
        'hour': '7:30 PM',
        'duration': '2 hours',
        'language': 'Italian',
        'meeting_point': 'Wine Bar',
        'price': '€35.00 per person',
        'image': 'https://images.pexels.com/photos/920382/pexels-photo-920382.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
]

madrid_tour_data = [
    {
        'id': 18,
        'title': 'Prado Museum Art Tour',
        'description': 'Immerse yourself in the world of Spanish art at the renowned Prado Museum, home to masterpieces by Velázquez, Goya, and El Greco.',
        'hour': '10:00 AM',
        'duration': '2.5 hours',
        'language': 'Spanish',
        'meeting_point': 'Prado Museum Entrance',
        'price': '€25.00 per person',
        'image': 'https://images.pexels.com/photos/2902056/pexels-photo-2902056.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 19,
        'title': 'Royal Palace of Madrid Guided Tour',
        'description': 'Explore the opulent rooms and grand architecture of the Royal Palace of Madrid, the official residence of the Spanish monarch.',
        'hour': '11:30 AM',
        'duration': '3 hours',
        'language': 'English',
        'meeting_point': 'Royal Palace Entrance',
        'price': '€30.00 per person',
        'image': 'https://images.pexels.com/photos/540368/pexels-photo-540368.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 20,
        'title': 'Retiro Park Bike Tour',
        'description': 'Cycle through the beautiful Retiro Park, exploring its lush gardens, serene lakes, and iconic landmarks with a local guide.',
        'hour': '3:00 PM',
        'duration': '2 hours',
        'language': 'Spanish',
        'meeting_point': 'Retiro Park Bike Rental',
        'price': '€18.00 per person',
        'image': 'https://images.pexels.com/photos/1704125/pexels-photo-1704125.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 21,
        'title': 'Tapas and Flamenco Night Experience',
        'description': 'Savor traditional Spanish tapas and immerse yourself in the passionate world of Flamenco with a night of delicious food and live music.',
        'hour': '8:00 PM',
        'duration': '4 hours',
        'language': 'English',
        'meeting_point': 'Local Tapas Bar',
        'price': '€35.00 per person',
        'image': 'https://images.pexels.com/photos/1798036/pexels-photo-1798036.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 22,
        'title': 'Madrid Segway City Tour',
        'description': 'Glide through the streets of Madrid on a Segway, exploring the citys main attractions and landmarks with a knowledgeable guide.',
        'hour': '2:30 PM',
        'duration': '2.5 hours',
        'language': 'Spanish',
        'meeting_point': 'Segway Tour Office',
        'price': '€28.00 per person',
        'image': 'https://images.pexels.com/photos/4069917/pexels-photo-4069917.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 23,
        'title': 'Madrid Wine Tasting: Vinos Españoles',
        'description': 'Indulge in a delightful wine tasting experience featuring a selection of Spanish wines, accompanied by expert guidance on flavors and pairings.',
        'hour': '6:00 PM',
        'duration': '2 hours',
        'language': 'English',
        'meeting_point': 'Wine Cellar',
        'price': '€22.00 per person',
        'image': 'https://images.pexels.com/photos/1024480/pexels-photo-1024480.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 24,
        'title': 'Madrid Street Art Walking Tour',
        'description': 'Discover the vibrant street art scene in the neighborhoods of Madrid, exploring colorful murals and urban art installations.',
        'hour': '4:30 PM',
        'duration': '2 hours',
        'language': 'Spanish',
        'meeting_point': 'Street Art Tour Meeting Point',
        'price': '€15.00 per person',
        'image': 'https://images.pexels.com/photos/1849851/pexels-photo-1849851.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 25,
        'title': 'Madrid Flamenco Show at Tablao',
        'description': 'Experience the intensity and passion of Flamenco with an authentic live show at a traditional Tablao in the heart of Madrid.',
        'hour': '9:30 PM',
        'duration': '1.5 hours',
        'language': 'English',
        'meeting_point': 'Tablao Flamenco Entrance',
        'price': '€20.00 per person',
        'image': 'https://images.pexels.com/photos/1514418/pexels-photo-1514418.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
]

berlin_tour_data = [
    {
        'id': 26,
        'title': 'Berlin Wall History Walking Tour',
        'description': 'Explore the history of the Berlin Wall, visiting key sites and learning about the events that shaped the city during the Cold War.',
        'hour': '10:30 AM',
        'duration': '3 hours',
        'language': 'German',
        'meeting_point': 'Checkpoint Charlie',
        'price': '€20.00 per person',
        'image': 'https://images.pexels.com/photos/2120781/pexels-photo-2120781.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 27,
        'title': 'Brandenburg Gate and Reichstag Tour',
        'description': 'Visit two iconic landmarks of Berlin, the Brandenburg Gate, and the Reichstag, while delving into the citys rich political history.',
        'hour': '2:00 PM',
        'duration': '2.5 hours',
        'language': 'English',
        'meeting_point': 'Brandenburg Gate',
        'price': '€25.00 per person',
        'image': 'https://images.pexels.com/photos/1449450/pexels-photo-1449450.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 28,
        'title': 'Berlin Bike Tour: Parks and Urban Landscapes',
        'description': 'Cycle through Berlins parks and urban landscapes, discovering the citys green spaces and modern architecture with a local guide.',
        'hour': '11:00 AM',
        'duration': '3 hours',
        'language': 'German',
        'meeting_point': 'Bike Rental Shop',
        'price': '€18.00 per person',
        'image': 'https://images.pexels.com/photos/5916764/pexels-photo-5916764.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 29,
        'title': 'Berlin Street Art Discovery Tour',
        'description': 'Embark on a walking tour to explore Berlins vibrant street art scene, discovering murals, graffiti, and the stories behind the artworks.',
        'hour': '3:30 PM',
        'duration': '2 hours',
        'language': 'English',
        'meeting_point': 'Street Art Tour Meeting Point',
        'price': '€15.00 per person',
        'image': 'https://images.pexels.com/photos/1467839/pexels-photo-1467839.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 30,
        'title': 'Berlin Currywurst Tasting Tour',
        'description': 'Savor the iconic Berlin Currywurst, exploring different local spots to taste variations of this beloved German street food.',
        'hour': '6:00 PM',
        'duration': '2 hours',
        'language': 'German',
        'meeting_point': 'Currywurst Tasting Station',
        'price': '€12.00 per person',
        'image': 'https://images.pexels.com/photos/1510859/pexels-photo-1510859.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 31,
        'title': 'East Side Gallery Graffiti Workshop',
        'description': 'Unleash your creativity in a graffiti workshop at the East Side Gallery, the longest remaining stretch of the Berlin Wall covered in art.',
        'hour': '4:00 PM',
        'duration': '2.5 hours',
        'language': 'English',
        'meeting_point': 'East Side Gallery Entrance',
        'price': '€30.00 per person',
        'image': 'https://images.pexels.com/photos/312473/pexels-photo-312473.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 32,
        'title': 'Berlin Tech and Innovation Tour',
        'description': 'Discover Berlins thriving tech scene, visiting innovative startups, co-working spaces, and learning about the citys tech history.',
        'hour': '1:30 PM',
        'duration': '3 hours',
        'language': 'German',
        'meeting_point': 'Tech Hub Berlin',
        'price': '€22.00 per person',
        'image': 'https://images.pexels.com/photos/775201/pexels-photo-775201.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 33,
        'title': 'Berlin Beer Garden Experience',
        'description': 'Enjoy a leisurely afternoon in one of Berlins traditional beer gardens, sampling local brews and soaking up the relaxed atmosphere.',
        'hour': '5:30 PM',
        'duration': '2 hours',
        'language': 'English',
        'meeting_point': 'Beer Garden Entrance',
        'price': '€18.00 per person',
        'image': 'https://images.pexels.com/photos/1070957/pexels-photo-1070957.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
]

lyon_tour_data = [
    {
        'id': 34,
        'title': 'Old Town (Vieux Lyon) Walking Tour',
        'description': 'Stroll through the charming cobblestone streets of Vieux Lyon, exploring historic landmarks, traboules, and enjoying the local atmosphere.',
        'hour': '10:00 AM',
        'duration': '2.5 hours',
        'language': 'French',
        'meeting_point': 'Vieux Lyon Square',
        'price': '€18.00 per person',
        'image': 'https://images.pexels.com/photos/1763817/pexels-photo-1763817.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 35,
        'title': 'Lyon Gastronomy Tour: Bouchon Experience',
        'description': 'Indulge in a culinary journey through Lyons renowned bouchons, savoring traditional Lyonnais dishes and regional specialties.',
        'hour': '12:30 PM',
        'duration': '3 hours',
        'language': 'English',
        'meeting_point': 'Bouchon Culinaire',
        'price': '€35.00 per person',
        'image': 'https://images.pexels.com/photos/1058237/pexels-photo-1058237.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 36,
        'title': 'Lyon Museum of Fine Arts Tour',
        'description': 'Explore the extensive collection of the Lyon Museum of Fine Arts, featuring masterpieces from various periods, styles, and artists.',
        'hour': '2:00 PM',
        'duration': '2 hours',
        'language': 'French',
        'meeting_point': 'Museum Entrance',
        'price': '€22.00 per person',
        'image': 'https://images.pexels.com/photos/427971/pexels-photo-427971.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 37,
        'title': 'Lyon River Cruise: Saône and Rhône',
        'description': 'Embark on a scenic river cruise along the Saône and Rhône rivers, admiring the picturesque views of Lyons landmarks from the water.',
        'hour': '4:30 PM',
        'duration': '1.5 hours',
        'language': 'English',
        'meeting_point': 'River Cruise Pier',
        'price': '€15.00 per person',
        'image': 'https://images.pexels.com/photos/1178709/pexels-photo-1178709.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 38,
        'title': 'Lyon Silk Workshop: Create Your Own Scarf',
        'description': 'Participate in a hands-on silk workshop, learning the art of silk painting and creating your own unique scarf to take home as a souvenir.',
        'hour': '3:00 PM',
        'duration': '2 hours',
        'language': 'French',
        'meeting_point': 'Silk Workshop Studio',
        'price': '€28.00 per person',
        'image': 'https://images.pexels.com/photos/1679649/pexels-photo-1679649.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 39,
        'title': 'Lyon Traboules Exploration Tour',
        'description': 'Discover the hidden traboules (passageways) of Lyon, navigating through secret passages and uncovering the fascinating history of these unique features.',
        'hour': '11:00 AM',
        'duration': '2.5 hours',
        'language': 'English',
        'meeting_point': 'Traboules Starting Point',
        'price': '€20.00 per person',
        'image': 'https://images.pexels.com/photos/1397645/pexels-photo-1397645.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 40,
        'title': 'Lyon Beaujolais Wine Tour',
        'description': 'Embark on a day trip to the nearby Beaujolais wine region, tasting exquisite wines and enjoying the picturesque vineyards of the French countryside.',
        'hour': '9:00 AM',
        'duration': '6 hours',
        'language': 'French',
        'meeting_point': 'Lyon Departure Point',
        'price': '€45.00 per person',
        'image': 'https://images.pexels.com/photos/1097420/pexels-photo-1097420.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 41,
        'title': 'Lyon Parc de la Tête d\'Or Pedal Boat Experience',
        'description': 'Relax on the tranquil waters of Parc de la Tête d\'Or with a pedal boat experience, surrounded by the beauty of the park and its wildlife.',
        'hour': '2:30 PM',
        'duration': '1.5 hours',
        'language': 'English',
        'meeting_point': 'Park Pedal Boat Rental',
        'price': '€12.00 per person',
        'image': 'https://images.pexels.com/photos/480301/pexels-photo-480301.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
]

zurich_tour_data = [
    {
        'id': 42,
        'title': 'Old Town (Altstadt) Walking Tour',
        'description': 'Discover the medieval charm of Zurichs Old Town, exploring narrow alleys, historical buildings, and iconic landmarks with a knowledgeable guide.',
        'hour': '10:00 AM',
        'duration': '2.5 hours',
        'language': 'German',
        'meeting_point': 'Old Town Square',
        'price': 'CHF 20.00 per person',
        'image': 'https://images.pexels.com/photos/327550/pexels-photo-327550.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 43,
        'title': 'Zurich Lake Cruise and City Panorama',
        'description': 'Embark on a scenic cruise on Lake Zurich, enjoying breathtaking views of the city skyline, the Swiss Alps, and the serene waters.',
        'hour': '2:30 PM',
        'duration': '2 hours',
        'language': 'English',
        'meeting_point': 'Lake Zurich Pier',
        'price': 'CHF 30.00 per person',
        'image': 'https://images.pexels.com/photos/3509917/pexels-photo-3509917.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 44,
        'title': 'Swiss Chocolate Tasting Tour',
        'description': 'Indulge your sweet tooth with a chocolate tasting tour, visiting Zurichs finest chocolate shops and learning about the Swiss chocolate-making tradition.',
        'hour': '11:00 AM',
        'duration': '2 hours',
        'language': 'German',
        'meeting_point': 'Chocolaterie Entrance',
        'price': 'CHF 25.00 per person',
        'image': 'https://images.pexels.com/photos/1666331/pexels-photo-1666331.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 45,
        'title': 'Zurich Art Museums Tour',
        'description': 'Immerse yourself in Zurichs vibrant art scene, visiting renowned art museums and galleries showcasing both classical and contemporary works.',
        'hour': '3:00 PM',
        'duration': '3 hours',
        'language': 'English',
        'meeting_point': 'Art Museum Entrance',
        'price': 'CHF 35.00 per person',
        'image': 'https://images.pexels.com/photos/267511/pexels-photo-267511.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 46,
        'title': 'Swiss Alps Day Trip: Rhine Falls and Winterthur',
        'description': 'Embark on a day trip to the spectacular Rhine Falls and the cultural city of Winterthur, exploring natural wonders and cultural treasures.',
        'hour': '9:00 AM',
        'duration': '6 hours',
        'language': 'German',
        'meeting_point': 'Zurich Departure Point',
        'price': 'CHF 50.00 per person',
        'image': 'https://images.pexels.com/photos/1866671/pexels-photo-1866671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 47,
        'title': 'Zurich Tech Innovation Walk',
        'description': 'Explore Zurichs thriving tech and innovation scene, visiting startup hubs, co-working spaces, and learning about the citys technological advancements.',
        'hour': '1:30 PM',
        'duration': '2.5 hours',
        'language': 'English',
        'meeting_point': 'Tech Hub Zurich',
        'price': 'CHF 28.00 per person',
        'image': 'https://images.pexels.com/photos/775201/pexels-photo-775201.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 48,
        'title': 'Zurich Botanical Garden Exploration',
        'description': 'Escape to the tranquility of Zurichs Botanical Garden, discovering a diverse collection of plants, flowers, and serene landscapes.',
        'hour': '4:30 PM',
        'duration': '2 hours',
        'language': 'German',
        'meeting_point': 'Botanical Garden Entrance',
        'price': 'CHF 18.00 per person',
        'image': 'https://images.pexels.com/photos/764860/pexels-photo-764860.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 49,
        'title': 'Zurich Street Food Market Experience',
        'description': 'Savor a variety of international and local delights at Zurichs vibrant street food market, exploring different stalls and flavors.',
        'hour': '6:00 PM',
        'duration': '2 hours',
        'language': 'English',
        'meeting_point': 'Street Food Market Entrance',
        'price': 'CHF 22.00 per person',
        'image': 'https://images.pexels.com/photos/2745951/pexels-photo-2745951.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
]

munich_tour_data = [
    {
        'id': 50,
        'title': 'Marienplatz and Old Town Walk',
        'description': 'Explore the historic Marienplatz and Old Town of Munich, discovering iconic landmarks, charming streets, and the rich history of the city.',
        'hour': '10:30 AM',
        'duration': '2.5 hours',
        'language': 'German',
        'meeting_point': 'Marienplatz Clock Tower',
        'price': '€15.00 per person',
        'image': 'https://images.pexels.com/photos/606540/pexels-photo-606540.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 51,
        'title': 'Munich Beer Gardens Tour',
        'description': 'Immerse yourself in Munichs beer culture with a guided tour of traditional beer gardens, tasting local brews and savoring Bavarian specialties.',
        'hour': '2:00 PM',
        'duration': '3 hours',
        'language': 'English',
        'meeting_point': 'Beer Garden Meeting Point',
        'price': '€25.00 per person',
        'image': 'https://images.pexels.com/photos/5938/food-summer-beer-garden.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 52,
        'title': 'Nymphenburg Palace and Gardens Tour',
        'description': 'Visit the magnificent Nymphenburg Palace, exploring its opulent rooms, beautiful gardens, and learning about Bavarian royalty.',
        'hour': '11:00 AM',
        'duration': '2.5 hours',
        'language': 'German',
        'meeting_point': 'Nymphenburg Palace Entrance',
        'price': '€30.00 per person',
        'image': 'https://images.pexels.com/photos/1170467/pexels-photo-1170467.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 53,
        'title': 'Munich Residenz Museum Tour',
        'description': 'Explore the grandeur of the Munich Residenz, the former royal palace of the Bavarian monarchs, featuring opulent rooms and priceless treasures.',
        'hour': '3:30 PM',
        'duration': '3 hours',
        'language': 'English',
        'meeting_point': 'Residenz Museum Entrance',
        'price': '€35.00 per person',
        'image': 'https://images.pexels.com/photos/4996052/pexels-photo-4996052.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 54,
        'title': 'Munich Viktualienmarkt Food Tour',
        'description': 'Savor the flavors of Munich at Viktualienmarkt, a bustling food market, tasting local delicacies, cheeses, sausages, and more.',
        'hour': '1:30 PM',
        'duration': '2 hours',
        'language': 'German',
        'meeting_point': 'Viktualienmarkt Fountain',
        'price': '€20.00 per person',
        'image': 'https://images.pexels.com/photos/317097/pexels-photo-317097.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 55,
        'title': 'Munich BMW Welt and Museum Visit',
        'description': 'Experience the world of BMW at BMW Welt and Museum, exploring the latest models, innovative exhibits, and the history of the iconic brand.',
        'hour': '4:00 PM',
        'duration': '2.5 hours',
        'language': 'English',
        'meeting_point': 'BMW Welt Entrance',
        'price': '€28.00 per person',
        'image': 'https://images.pexels.com/photos/7650/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 56,
        'title': 'Munich Englischer Garten Bike Tour',
        'description': 'Cycle through the expansive Englischer Garten, Munichs famous city park, enjoying scenic landscapes, lakes, and the iconic Chinese Tower.',
        'hour': '2:30 PM',
        'duration': '2 hours',
        'language': 'German',
        'meeting_point': 'Bike Rental Shop',
        'price': '€18.00 per person',
        'image': 'https://images.pexels.com/photos/365292/pexels-photo-365292.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 57,
        'title': 'Munich Dachau Memorial Tour',
        'description': 'Visit the Dachau Concentration Camp Memorial Site, reflecting on the historical significance and paying respects to the victims of the Holocaust.',
        'hour': '10:00 AM',
        'duration': '4 hours',
        'language': 'English',
        'meeting_point': 'Dachau Memorial Entrance',
        'price': '€22.00 per person',
        'image': 'https://images.pexels.com/photos/442042/pexels-photo-442042.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
]

paris_tour_data = [
    {
        'id': 58,
        'title': 'Eiffel Tower and Seine River Cruise',
        'description': 'Experience the iconic Eiffel Tower with a guided tour, followed by a scenic Seine River cruise offering breathtaking views of Paris landmarks.',
        'hour': '9:30 AM',
        'duration': '3 hours',
        'language': 'French',
        'meeting_point': 'Eiffel Tower Entrance',
        'price': '€30.00 per person',
        'image': 'https://images.pexels.com/photos/2802352/pexels-photo-2802352.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 59,
        'title': 'Louvre Museum Art Expedition',
        'description': 'Embark on an art-filled journey through the Louvre Museum, exploring masterpieces such as the Mona Lisa, Venus de Milo, and more.',
        'hour': '2:00 PM',
        'duration': '4 hours',
        'language': 'English',
        'meeting_point': 'Louvre Museum Pyramid Entrance',
        'price': '€35.00 per person',
        'image': 'https://images.pexels.com/photos/40984/louvre-pyramid-paris-architecture-40984.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 60,
        'title': 'Montmartre Artists Quarter Tour',
        'description': 'Wander through the charming streets of Montmartre, the artists quarter, discovering the history, art studios, and the iconic Sacré-Cœur Basilica.',
        'hour': '11:00 AM',
        'duration': '2.5 hours',
        'language': 'French',
        'meeting_point': 'Montmartre Square',
        'price': '€25.00 per person',
        'image': 'https://images.pexels.com/photos/774349/pexels-photo-774349.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 61,
        'title': 'Versailles Palace and Gardens Day Trip',
        'description': 'Embark on a day trip to the opulent Palace of Versailles, exploring the grand halls, intricate gardens, and the Hall of Mirrors.',
        'hour': '8:30 AM',
        'duration': '6 hours',
        'language': 'English',
        'meeting_point': 'Versailles Palace Entrance',
        'price': '€50.00 per person',
        'image': 'https://images.pexels.com/photos/3968944/pexels-photo-3968944.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 62,
        'title': 'Parisian Culinary Adventure: Food Tasting',
        'description': 'Savor the flavors of Paris with a culinary adventure, tasting a variety of French delicacies, pastries, cheeses, and wines.',
        'hour': '3:30 PM',
        'duration': '2 hours',
        'language': 'French',
        'meeting_point': 'Gourmet Food Market',
        'price': '€28.00 per person',
        'image': 'https://images.pexels.com/photos/2132551/pexels-photo-2132551.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 63,
        'title': 'Paris Opera House Guided Tour',
        'description': 'Step into the world of elegance at the Paris Opera House, exploring its stunning architecture, rich history, and grand performance spaces.',
        'hour': '1:30 PM',
        'duration': '2.5 hours',
        'language': 'English',
        'meeting_point': 'Opera House Main Entrance',
        'price': '€22.00 per person',
        'image': 'https://images.pexels.com/photos/1101182/pexels-photo-1101182.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 64,
        'title': 'Seine Dinner Cruise with City Lights',
        'description': 'Indulge in a romantic dinner cruise along the Seine River, enjoying delicious cuisine while admiring the illuminated landmarks of Paris.',
        'hour': '7:00 PM',
        'duration': '3 hours',
        'language': 'French',
        'meeting_point': 'Seine River Cruise Pier',
        'price': '€45.00 per person',
        'image': 'https://images.pexels.com/photos/315673/pexels-photo-315673.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 65,
        'title': 'Sainte-Chapelle and Notre-Dame Cathedral Tour',
        'description': 'Discover the breathtaking stained glass of Sainte-Chapelle and the Gothic architecture of Notre-Dame Cathedral on this historical tour.',
        'hour': '10:00 AM',
        'duration': '2.5 hours',
        'language': 'English',
        'meeting_point': 'Sainte-Chapelle Entrance',
        'price': '€18.00 per person',
        'image': 'https://images.pexels.com/photos/3943316/pexels-photo-3943316.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
]

ljubljana_tour_data = [
    {
        'id': 66,
        'title': 'Ljubljana Castle and Old Town Walk',
        'description': 'Discover the historic charm of Ljubljana with a guided tour of Ljubljana Castle and a stroll through the cobblestone streets of the Old Town.',
        'hour': '10:30 AM',
        'duration': '2.5 hours',
        'language': 'Slovenian',
        'meeting_point': 'Castle Funicular Station',
        'price': '€20.00 per person',
        'image': 'https://images.pexels.com/photos/2326929/pexels-photo-2326929.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 67,
        'title': 'Ljubljana River Cruise and Bridges Tour',
        'description': 'Experience the beauty of Ljubljana from the water with a river cruise, passing under picturesque bridges and enjoying the citys architecture.',
        'hour': '2:00 PM',
        'duration': '2 hours',
        'language': 'English',
        'meeting_point': 'River Cruise Dock',
        'price': '€15.00 per person',
        'image': 'https://images.pexels.com/photos/3006886/pexels-photo-3006886.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 68,
        'title': 'Ljubljana Art and Design District Tour',
        'description': 'Explore Ljubljanas vibrant art and design district, visiting galleries, street art installations, and learning about the citys creative scene.',
        'hour': '11:00 AM',
        'duration': '3 hours',
        'language': 'Slovenian',
        'meeting_point': 'Art District Entrance',
        'price': '€25.00 per person',
        'image': 'https://images.pexels.com/photos/442556/pexels-photo-442556.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 69,
        'title': 'Ljubljana Culinary Walking Tour',
        'description': 'Indulge in a culinary journey through Ljubljana, tasting traditional Slovenian dishes, local wines, and exploring the citys food markets.',
        'hour': '3:30 PM',
        'duration': '2 hours',
        'language': 'English',
        'meeting_point': 'Central Market Square',
        'price': '€18.00 per person',
        'image': 'https://images.pexels.com/photos/1681469/pexels-photo-1681469.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 70,
        'title': 'Ljubljana Tivoli Park Bike Tour',
        'description': 'Cycle through the green oasis of Tivoli Park, exploring scenic pathways, rose gardens, and the cultural sights within Ljubljana\'s largest park.',
        'hour': '2:30 PM',
        'duration': '2 hours',
        'language': 'Slovenian',
        'meeting_point': 'Bike Rental Shop',
        'price': '€22.00 per person',
        'image': 'https://images.pexels.com/photos/2375805/pexels-photo-2375805.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 71,
        'title': 'Ljubljana Open-Air Museum Tour',
        'description': 'Step back in time with a visit to Ljubljana\'s Open-Air Museum, exploring traditional Slovenian architecture, crafts, and rural life.',
        'hour': '1:30 PM',
        'duration': '3 hours',
        'language': 'English',
        'meeting_point': 'Open-Air Museum Entrance',
        'price': '€20.00 per person',
        'image': 'https://images.pexels.com/photos/442559/pexels-photo-442559.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 72,
        'title': 'Ljubljana Dragon Bridge and Castle Night Tour',
        'description': 'Experience the enchanting atmosphere of Ljubljana at night, with a guided tour of the Dragon Bridge and Ljubljana Castle under the city lights.',
        'hour': '8:00 PM',
        'duration': '2.5 hours',
        'language': 'Slovenian',
        'meeting_point': 'Dragon Bridge',
        'price': '€28.00 per person',
        'image': 'https://images.pexels.com/photos/1156557/pexels-photo-1156557.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 73,
        'title': 'Ljubljana National Gallery Art Tour',
        'description': 'Immerse yourself in the world of Slovenian art at the National Gallery, exploring a diverse collection of paintings, sculptures, and installations.',
        'hour': '10:00 AM',
        'duration': '2 hours',
        'language': 'English',
        'meeting_point': 'National Gallery Entrance',
        'price': '€15.00 per person',
        'image': 'https://images.pexels.com/photos/442558/pexels-photo-442558.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
]

marseille_tour_data = [
    {
        'id': 74,
        'title': 'Old Port (Vieux-Port) Walking Tour',
        'description': 'Explore the historic Old Port of Marseille, discovering its picturesque waterfront, lively markets, and iconic landmarks with a knowledgeable guide.',
        'hour': '10:30 AM',
        'duration': '2.5 hours',
        'language': 'French',
        'meeting_point': 'Old Port Entrance',
        'price': '€20.00 per person',
        'image': 'https://images.pexels.com/photos/2061723/pexels-photo-2061723.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 75,
        'title': 'Calanques National Park Hiking Excursion',
        'description': 'Embark on a scenic hike through the Calanques National Park, exploring rugged coastal landscapes, hidden coves, and pristine natural beauty.',
        'hour': '2:00 PM',
        'duration': '4 hours',
        'language': 'English',
        'meeting_point': 'Calanques Visitor Center',
        'price': '€35.00 per person',
        'image': 'https://images.pexels.com/photos/2048158/pexels-photo-2048158.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 76,
        'title': 'Marseille Mucem Museum and Fort Saint-Jean Tour',
        'description': 'Discover the cultural treasures of Marseille at the Mucem Museum and Fort Saint-Jean, exploring contemporary exhibits and historical fortifications.',
        'hour': '11:00 AM',
        'duration': '3 hours',
        'language': 'French',
        'meeting_point': 'Mucem Museum Entrance',
        'price': '€25.00 per person',
        'image': 'https://images.pexels.com/photos/2061724/pexels-photo-2061724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 77,
        'title': 'Marseille Street Food Tasting',
        'description': 'Indulge in the diverse flavors of Marseille with a street food tasting tour, sampling local specialties, seafood, and Mediterranean delights.',
        'hour': '3:30 PM',
        'duration': '2 hours',
        'language': 'English',
        'meeting_point': 'Street Food Market',
        'price': '€18.00 per person',
        'image': 'https://images.pexels.com/photos/255447/pexels-photo-255447.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 78,
        'title': 'Marseille Boat Tour to Château d\'If',
        'description': 'Embark on a boat tour to the famous Château d\'If, the historic island fortress, and learn about its intriguing history and literary connections.',
        'hour': '2:30 PM',
        'duration': '2 hours',
        'language': 'French',
        'meeting_point': 'Old Port Pier',
        'price': '€22.00 per person',
        'image': 'https://images.pexels.com/photos/2048159/pexels-photo-2048159.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 79,
        'title': 'Marseille Basilique Notre-Dame de la Garde Tour',
        'description': 'Visit the iconic Basilique Notre-Dame de la Garde, enjoying panoramic views of Marseille and the Mediterranean Sea from the city\'s highest point.',
        'hour': '1:30 PM',
        'duration': '2.5 hours',
        'language': 'English',
        'meeting_point': 'Basilica Entrance',
        'price': '€28.00 per person',
        'image': 'https://images.pexels.com/photos/2048160/pexels-photo-2048160.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 80,
        'title': 'Marseille Mediterranean History Museum Visit',
        'description': 'Immerse yourself in the rich history of the Mediterranean at Marseille\'s History Museum, exploring artifacts, exhibits, and maritime heritage.',
        'hour': '4:30 PM',
        'duration': '2 hours',
        'language': 'French',
        'meeting_point': 'History Museum Entrance',
        'price': '€15.00 per person',
        'image': 'https://images.pexels.com/photos/2048161/pexels-photo-2048161.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
    {
        'id': 81,
        'title': 'Marseille Frioul Archipelago Kayak Adventure',
        'description': 'Embark on a thrilling kayak adventure around the Frioul Archipelago, exploring hidden coves, sea caves, and the crystal-clear waters of the Mediterranean.',
        'hour': '9:00 AM',
        'duration': '3 hours',
        'language': 'English',
        'meeting_point': 'Kayak Rental Center',
        'price': '€30.00 per person',
        'image': 'https://images.pexels.com/photos/2048162/pexels-photo-2048162.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'url': '',
    },
]
