# Generated by Django 4.2.7 on 2023-11-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivalv', '0002_alter_tour_id_alter_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
