# Generated by Django 4.2.7 on 2023-11-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivalv', '0004_alter_tour_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coworking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=70)),
                ('socials', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=70)),
                ('socials', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalConsume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=70)),
                ('socials', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=70)),
                ('socials', models.URLField()),
            ],
        ),
    ]
