# Generated by Django 4.2.7 on 2023-11-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivalv', '0005_coworking_hotels_localconsume_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
