const tourData = [
    {
      id: 1,
      title: 'Coyoacán & Frida Kahlo Free Walking Tour in Mexico City',
      description: 'Enjoy the enchanted blocks around the famed "Blue House" where the wonderful Mexican artist Frida Kahlo used to live, and learn how she became a significant icon around the world.',
      hour: '2:30 PM',
      duration: '2.5 hours',
      language: 'English',
      meetingPoint: "Frida Kahlo's Museum",
      price: 'Based on tips',
    },
    {
      id: 2,
      title: 'Teotihuacan Pyramids Guided Tour',
      description: 'Explore the ancient Teotihuacan Pyramids, a UNESCO World Heritage site, and learn about the fascinating history and culture of this ancient city.',
      hour: '9:00 AM',
      duration: '4 hours',
      language: 'Spanish',
      meetingPoint: 'Teotihuacan Visitor Center',
      price: '$30.00 per person',
    },
    {
      id: 3,
      title: 'Chapultepec Castle and Park Tour',
      description: 'Discover the history and elegance of Chapultepec Castle, situated in the heart of Chapultepec Park, and enjoy a stroll through the beautiful surrounding gardens.',
      hour: '11:00 AM',
      duration: '3 hours',
      language: 'English',
      meetingPoint: 'Chapultepec Castle Entrance',
      price: '$25.00 per person',
    },
    {
      id: 4,
      title: 'Xochimilco Floating Gardens Boat Tour',
      description: 'Experience the vibrant colors and cultural richness of Xochimilco as you navigate its picturesque canals on a traditional trajinera boat.',
      hour: '1:00 PM',
      duration: '2 hours',
      language: 'Spanish',
      meetingPoint: 'Xochimilco Dock',
      price: '$20.00 per person',
    },
    {
      id: 5,
      title: 'Zócalo and Historic Center Walking Tour',
      description: 'Walk through the historic heart of Mexico City, the Zócalo, and explore its iconic landmarks, including the Metropolitan Cathedral and the National Palace.',
      hour: '10:30 AM',
      duration: '2.5 hours',
      language: 'English',
      meetingPoint: 'Zócalo Square',
      price: '$15.00 per person',
    },
    {
      id: 6,
      title: 'Street Food Tasting in La Merced Market',
      description: 'Embark on a culinary adventure in the bustling La Merced Market, tasting a variety of authentic Mexican street foods and flavors.',
      hour: '6:00 PM',
      duration: '2 hours',
      language: 'Spanish',
      meetingPoint: 'La Merced Market Entrance',
      price: '$18.00 per person',
    },
    {
      id: 7,
      title: 'National Museum of Anthropology Guided Tour',
      description: 'Explore the extensive collection of pre-Columbian artifacts and learn about the diverse cultures that shaped the history of Mexico at the National Museum of Anthropology.',
      hour: '3:00 PM',
      duration: '3 hours',
      language: 'English',
      meetingPoint: 'National Museum of Anthropology Entrance',
      price: '$22.00 per person',
    },
  ];
  
export default tourData
  