# Generated by Django 4.2.7 on 2023-11-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivalv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
